name: ai_in_medicine
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python
  - pip
  - jupyter
  - jupyterlab
  - notebook
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - rdkit
  - cpuonly
  - pytorch==1.13.1
  - tensorflow
  - nibabel
