name: ai_in_medicine
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - jupyter
  - jupyterlab
  - notebook
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - rdkit
  - pytorch torchvision torchaudio cpuonly -c pytorch
  - tensorflow
  - nibabel
