name: ai_in_medicine
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - jupyter
  - jupyterlab
  - notebook
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - rdkit
  - torch-1.13.1+cpu-cp310-cp310-linux_x86_64.whl
  - tensorflow
  - nibabel
