name: ai_in_medicine
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - jupyter
  - jupyterlab
  - notebook
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - rdkit
  --find-links https://download.pytorch.org/whl/torch_stable.html
  - torch==1.13.1+cpu
  - tensorflow
  - nibabel
